import pytest

from app.core.config import settings
from app.core.security import _validate_init_data
from scripts.gen_auth import generate_init_data


def test_generate_and_validate_auth():
    """
    Ensures that the string generated by the script is accepted by the
    application's internal validator.
    """
    bot_token = settings.bot_token
    user_id = 999888
    username = "test_user"

    # Generate the string using the script's logic
    init_data = generate_init_data(bot_token=bot_token, user_id=user_id, username=username)

    # Validate using the app's logic
    user_payload = _validate_init_data(init_data)

    assert user_payload["id"] == user_id
    assert user_payload["username"] == username


def test_generate_auth_with_all_fields():
    """
    Test generating auth with all optional fields provided.
    """
    bot_token = settings.bot_token
    user_id = 123
    username = "full_user"
    first_name = "Alice"
    last_name = "Smith"
    auth_date = 1700000000

    init_data = generate_init_data(
        bot_token=bot_token,
        user_id=user_id,
        username=username,
        first_name=first_name,
        last_name=last_name,
        auth_date=auth_date,
    )

    user_payload = _validate_init_data(init_data)

    assert user_payload["id"] == user_id
    assert user_payload["username"] == username
    assert user_payload["first_name"] == first_name
    assert user_payload["last_name"] == last_name

    # Check if auth_date is present in the raw string (it's not in the user json)
    assert f"auth_date={auth_date}" in init_data


def test_invalid_bot_token_fails():
    """
    Ensures that if the script uses a different token, validation fails.
    """
    real_token = settings.bot_token
    fake_token = "12345:fake_token"

    init_data = generate_init_data(bot_token=fake_token, user_id=123)

    with pytest.raises(Exception) as excinfo:
        _validate_init_data(init_data)

    assert "Invalid initData signature" in str(excinfo.value)
